### ISSUE TITLE
Had to type each sentence in quotes.

### ISSUE THREAD

**Issue by NuthanReddy** [jezhiggins/eliza.py#2]

**Comment by trebitzki** [comment]
I have the same issue. Using python 2.7 on macports.

**Comment by trebitzki** [comment]
I just did
```
$ cd Downloads/eliza.py-master
$ python eliza.py
... intro ...
Hello.  How are you feeling today?
> OK, I guess
Traceback (most recent call last):
  File "eliza.py", line 313, in <module>
    command_interface()
  File "eliza.py", line 303, in command_interface
    s = input('> ')
  File "<string>", line 1
    OK, I guess
              ^
SyntaxError: unexpected EOF while parsing


```
